src: avoid using expect() in main method
Use of this results in unplesant output being presented to users:

  $ tas_agent

  thread 'main' (4143510) panicked at src/main.rs:130:10:
  unable to read API key from "config/api-key": Os { code: 2, kind: NotFound, message: "No such file or directory" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

With the new approach it shows:

  $ tas_agent
  unable to read API key from "config/api-key": No such file or directory (os error 2)

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>